name = "Peano"
defaultTargets = ["Main"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.17.0"

[[require]]
name = "aesop"
git = "https://github.com/leanprover-community/aesop.git"
rev = "v4.17.0"

[[lean_lib]]
name = "PeanoLib"
srcDir = "lean"

[[lean_exe]]
name = "Main"
srcDir = "lean"
supportInterpeter = true
